# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
black_version: 20.8b1
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Shopinvader
org_slug: shopinvader
prettify_xml: true
python_line_length: 88
rebel_module_groups: []
repo_description: null
repo_name: null
repo_slug: odoo-shopinvader
repo_website: https://github.com/shopinvader/odoo-shopinvader
travis_apt_packages: []
travis_apt_sources: []
